db:
  image: mysql:local
  volumes:
    - /Users/tung1404/Documents/docker/docker-mysql-phpmyadmin/data:/var/lib/mysql:rw
  ports:
    - "13306:3306"

phpmyadmin:
  image: nazarpc/phpmyadmin
  ports:
    - "8181:80"
  links:
    - db:mysql
